### ISSUE TITLE
errors after installation

### ISSUE THREAD

**Issue by hellozappa** [leonbarrett/BeanstalkCommandLine#10]
I keep getting: "beanstalk: -m is not a valid option" when entering: "beanstalk -m repo:list" and cannot seem to figure out why. I was also getting prompted for my benstalk creds over and over again too. Any ideas? I checked permissions, my login creds are saved in the config file properly...I'm lost.

**Comment by leonbarrett** [comment]
Hi, couple of questions:

What OS are you running
Do you have PHP with CLI installed and what version is it?
Where is the script installed

Thanks

**Comment by hellozappa** [comment]
Wow, Leon...SO sorry, I never saw this reply 11 months ago! I'm no longer using Beanstalk so don't need help with this anymore.
