### ISSUE TITLE
Server Environment Not Found

### ISSUE THREAD

**Issue by benlilley** [leonbarrett/BeanstalkCommandLine#4]
First I just wanted to say thank you for building this, was so stoked when I found it. I have run into an issue though, everything seems to be working until I go to do a deploy, here's the issue I ran into:

``` shell
Last commit: 11th Jul 2012 @ 03:36

Release Environments: (2)
    Staging (478f5045d56afb0e49a950e939fb6d4717b66026)
    Live (a442c6af893d421049bcf7a0cd0893c8619610ce)
Please enter an Environment name to deploy: Live
Please enter an revision number to deploy OR leave blank to deploy the latest revision: 
Please enter a release comment (optional): 
You are about to deploy Revision  to Live, are you sure you want to continue? y/n: y

ERROR: Errors
ERROR: Server Environment with "" is not found
```

Any ideas why this would be happening? Hopefully I'm not doing anything too stupid! Thanks.

**Comment by leonbarrett** [comment]
Hi, 

Thanks for the message, I've just updated the script for a smoother way of selecting an environment, so you can now type a number rather than the whole thing.

Could you give this a try and see if it works for you?

Thanks

**Comment by benlilley** [comment]
Thanks for that, funny enough that fixes the issue! Out of interest why does that sort the issue, I typed the Environment name correctly I thought?

**Comment by benlilley** [comment]
Sorry, while I'm at it I have another question! I installed the executable in /usr/bin but it is storing the beanstalk_cli.config file in my home folder which I'm not so keen on as I can see it in my Finder windows. Is there a way to store this elsewhere?

Thanks again.

**Comment by leonbarrett** [comment]
Hi Ben,

I think it may have been a change in the API as this used to work before. 

The path to the config can be changed by editing line 148 and adding a path of your choosing. I'm looking at a better way of storing the credentials, such as in keychain so will let you know when there is an update.

Thanks again, Leon
