### ISSUE TITLE
Repo list returns incorrect URLs

### ISSUE THREAD

**Issue by brodkin** [leonbarrett/BeanstalkCommandLine#5]
The `beanstalk repo:list` command returns incorrect urls for the repositories for two reasons:
1. The required period is missing between the subdomain and the beanstalkapp.com TLD.
2. The TLD beanstalkapp.com is misspelled as beanstakapp.com

**Comment by deplorableword** [comment]
doh, this is now fixed

**Comment by brodkin** [comment]
Wow, you're fast!
